- name: SSH Commands
  uses: appleboy/ssh-action@v0.0.2
    with:
      host: ${{ secrets.HOST }}
      username: ${{ secrets.USERNAME }}
      password: ${{ secrets.PASSWORD }}
      port: ${{ secrets.PORT }}
      script: whoami